In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
# Aim is to predict the marks of students of the test data

In [88]:
# Use the file namd 'training data' to train the model

data = pd.read_excel('Training_data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)
# print(y_train)
# Try plotting y_train with different features
# To get an idea whether to add some features or not
# Add some features if required in x_train

# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM



def feature_changing(x_train):
   # Label encoding for categorical features
    label_encoder=LabelEncoder()
    x_train[:,0]=label_encoder.fit_transform(x_train[:,0])
    x_train[:,1]=label_encoder.fit_transform(x_train[:,1])
    return x_train


x_train = feature_changing(x_train)
print("printing x_train after doing the feature changing \n",x_train)


printing x_train after doing the feature changing 
 [[0 1 2 ... 6 18 118]
 [1 1 2 ... 7 19 107]
 [1 1 3 ... 5 18 108]
 ...
 [1 1 2 ... 5 17 123]
 [1 0 1 ... 8 17 104]
 [1 1 1 ... 6 18 128]]


In [89]:
def z_score(x_train):

  # ---------
    # write the code for feature scaling here
    # Your code here
  # ---------
    x_mean = np.mean(x_train, axis=0)
    x_std = np.std(x_train, axis=0)
    
    # Apply Z-score normalization
    x_train_scaled = (x_train - x_mean) / x_std

    return x_train_scaled,x_std,x_mean

In [90]:
def cost(x_train, y_train, w, b):
    # Number of training examples
    m = x_train.shape[0]
    
    # Compute the predictions
    predictions = np.dot(x_train, w) + b
    
    # Compute the Mean Squared Error (MSE)
    loss = np.sum((predictions - y_train) ** 2) / (2 * m)
    
    return loss

In [91]:
def gradient_descent(x_train,y_train,w,b):

    m=x_train.shape[0]
    predictions = np.dot(x_train, w) + b
    errors = predictions - y_train
    learning_rate=0.5
    w_gradient = (1/m) * np.dot(x_train.T, errors)
    b_gradient = (1/m) * np.sum(errors)
    max_grad = 1.0
    w_gradient = np.clip(w_gradient, -max_grad, max_grad)
    b_gradient = np.clip(b_gradient, -max_grad, max_grad)

    w = w - learning_rate * w_gradient
    b = b - learning_rate * b_gradient

    return w, b

In [92]:
x_train = x_train.astype(np.float64)
x_train,x_std,x_mean = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)

x_predict = pd.read_excel('Test_data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test_data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w) + b

accuracy = 0
for dim in range(len(ans)):
    if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
        accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")

Congratulations, your accuracy is 100.0%
